use super::{opcode, Ident, literal, Register};

pub enum Instruction {
    NoOp,
    InputC(opcode::InputC),
    InputCF(opcode::InputCF),
    InputD(opcode::InputD),
    InputDF(opcode::InputDF),
    Move(Register, Register),
    LoadI(Register, literal::Byte),
    LoadP(opcode::LoadP),
    Add(Register, Register),
    AddI(Register, literal::Byte),
    Sub(Register, Register),
    SubI(Register, literal::Byte),
    Load(opcode::Load),
    LoadF(opcode::LoadF),
    Store(opcode::Store),
    StoreF(opcode::StoreF),
    ShiftL(Register),
    ShiftR(Register),
    Cmp(Register, Register),
    Jump(Ident),
    BrE(Ident),
    BrNE(Ident),
    BrG(Ident),
    BrGE(Ident),
}
