use super::{opcode, Ident, Literal, Register};

pub enum Instruction {
    NoOp(opcode::NoOp),
    InputC(opcode::InputC),
    InputCF(opcode::InputCF),
    InputD(opcode::InputD),
    InputDF(opcode::InputDF),
    Move(opcode::Move, Register, Register),
    LoadI(opcode::LoadI, Register, Literal),
    LoadP(opcode::LoadP),
    Add(opcode::Add, Register, Register),
    AddI(opcode::AddI, Register, Literal),
    Sub(opcode::Sub, Register, Register),
    SubI(opcode::SubI, Register, Literal),
    Load(opcode::Load),
    LoadF(opcode::LoadF),
    Store(opcode::Store),
    StoreF(opcode::StoreF),
    ShiftL(opcode::ShiftL, Register),
    ShiftR(opcode::ShiftR, Register),
    Cmp(opcode::Cmp, Register, Register),
    Jump(opcode::Jump, Ident),
    BrE(opcode::BrE, Ident),
    BrNE(opcode::BrNE, Ident),
    BrG(opcode::BrG, Ident),
    BrGE(opcode::BrGE, Ident),
}
