[package]
name = "i281_ast"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1"
miette = "5"
nom = "7"
nom_locate = { version = "4", features = ["runtime-dispatch-simd"] }
serde = { version = "1", features = ["derive"], optional = true }
