[package]
name = "i281_ast"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6"
i281_core = { path = "../i281_core" }

serde = { version = "1", features = ["derive"], optional = true }
